2020-06-05 03:55:20,694 ERROR: Exception on /messages [GET] [in c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Microsoft\Desktop\Microblog\app\main\routes.py", line 162, in messages
    messages = current_user.messages.recieved.order_by(
  File "c:\users\microsoft\microblog\env\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'messages'
2020-06-05 03:56:52,848 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:82]
2020-06-05 03:56:56,754 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:82]
2020-06-05 03:56:59,495 ERROR: Exception on /messages [GET] [in c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Microsoft\Desktop\Microblog\app\main\routes.py", line 164, in messages
    current_app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2020-06-05 03:57:22,200 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:82]
2020-06-05 03:57:25,243 ERROR: Exception on /messages [GET] [in c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Microsoft\Desktop\Microblog\app\main\routes.py", line 169, in messages
    return render_template('messages.html', messages=messages.items,
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Microsoft\Desktop\Microblog\app\templates\messages.html", line 19, in template
    {{ 'Older messages' }} <span aria-hidden="true">&rarr;</span>
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-06-05 03:58:54,401 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:82]
2020-06-05 03:58:57,508 ERROR: Exception on /messages [GET] [in c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Microsoft\Desktop\Microblog\app\main\routes.py", line 169, in messages
    return render_template('messages.html', messages=messages.items,
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\microsoft\microblog\env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Microsoft\Desktop\Microblog\app\templates\messages.html", line 1, in top-level template code
    {% extends base.html %}
  File "c:\users\microsoft\microblog\env\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'base' is undefined
2020-06-05 03:59:20,456 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:82]
2020-06-05 04:01:29,018 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:82]
2020-06-05 04:02:40,853 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:82]
2020-06-05 04:05:25,905 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:82]
2020-06-05 04:11:20,121 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:82]
2020-06-05 04:15:02,234 INFO: Microblog startup [in C:\Users\Microsoft\Desktop\Microblog\app\__init__.py:82]
